services:
  - type: web
    name: prioqueue
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/prioqueue/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
